// <auto-generated />
using System;
using GBCSporting2021_FD_Crew.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GBCSporting2021_FD_Crew.Migrations
{
    [DbContext(typeof(SportsProContext))]
    partial class SportsProContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GBCSporting2021_FD_Crew.Models.Country", b =>
                {
                    b.Property<string>("CountryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CountryCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CountryId");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            CountryId = "AFG",
                            CountryCode = "004",
                            CountryName = "Afghanistan"
                        },
                        new
                        {
                            CountryId = "ALA",
                            CountryCode = "248",
                            CountryName = "Åland Islands"
                        },
                        new
                        {
                            CountryId = "ALB",
                            CountryCode = "008",
                            CountryName = "Albania"
                        },
                        new
                        {
                            CountryId = "DZA",
                            CountryCode = "012",
                            CountryName = "Algeria"
                        },
                        new
                        {
                            CountryId = "ASM",
                            CountryCode = "016",
                            CountryName = "American Samoa"
                        },
                        new
                        {
                            CountryId = "AND",
                            CountryCode = "020",
                            CountryName = "Andorra"
                        },
                        new
                        {
                            CountryId = "AGO",
                            CountryCode = "024",
                            CountryName = "Angola"
                        },
                        new
                        {
                            CountryId = "AIA",
                            CountryCode = "660",
                            CountryName = "Anguilla"
                        },
                        new
                        {
                            CountryId = "ATA",
                            CountryCode = "010",
                            CountryName = "Antarctica"
                        },
                        new
                        {
                            CountryId = "ATG",
                            CountryCode = "028",
                            CountryName = "Antigua and Barbuda"
                        },
                        new
                        {
                            CountryId = "ARG",
                            CountryCode = "032",
                            CountryName = "Argentina"
                        },
                        new
                        {
                            CountryId = "ARM",
                            CountryCode = "051",
                            CountryName = "Armenia"
                        },
                        new
                        {
                            CountryId = "ABW",
                            CountryCode = "533",
                            CountryName = "Aruba"
                        },
                        new
                        {
                            CountryId = "AUS",
                            CountryCode = "036",
                            CountryName = "Australia"
                        },
                        new
                        {
                            CountryId = "AUT",
                            CountryCode = "040",
                            CountryName = "Austria"
                        },
                        new
                        {
                            CountryId = "AZE",
                            CountryCode = "031",
                            CountryName = "Azerbaijan"
                        },
                        new
                        {
                            CountryId = "BHS",
                            CountryCode = "044",
                            CountryName = "Bahamas"
                        },
                        new
                        {
                            CountryId = "BHR",
                            CountryCode = "048",
                            CountryName = "Bahrain"
                        },
                        new
                        {
                            CountryId = "BGD",
                            CountryCode = "050",
                            CountryName = "Bangladesh"
                        },
                        new
                        {
                            CountryId = "BRB",
                            CountryCode = "052",
                            CountryName = "Barbados"
                        },
                        new
                        {
                            CountryId = "BLR",
                            CountryCode = "112",
                            CountryName = "Belarus"
                        },
                        new
                        {
                            CountryId = "BEL",
                            CountryCode = "056",
                            CountryName = "Belgium"
                        },
                        new
                        {
                            CountryId = "BLZ",
                            CountryCode = "084",
                            CountryName = "Belize"
                        },
                        new
                        {
                            CountryId = "BEN",
                            CountryCode = "204",
                            CountryName = "Benin"
                        },
                        new
                        {
                            CountryId = "BMU",
                            CountryCode = "060",
                            CountryName = "Bermuda"
                        },
                        new
                        {
                            CountryId = "BTN",
                            CountryCode = "064",
                            CountryName = "Bhutan"
                        },
                        new
                        {
                            CountryId = "BOL",
                            CountryCode = "068",
                            CountryName = "Bolivia (Plurinational State of)"
                        },
                        new
                        {
                            CountryId = "BES",
                            CountryCode = "535",
                            CountryName = "Bonaire, Sint Eustatius and Saba"
                        },
                        new
                        {
                            CountryId = "BIH",
                            CountryCode = "070",
                            CountryName = "Bosnia and Herzegovina"
                        },
                        new
                        {
                            CountryId = "BWA",
                            CountryCode = "072",
                            CountryName = "Botswana"
                        },
                        new
                        {
                            CountryId = "BVT",
                            CountryCode = "074",
                            CountryName = "Bouvet Island"
                        },
                        new
                        {
                            CountryId = "BRA",
                            CountryCode = "076",
                            CountryName = "Brazil"
                        },
                        new
                        {
                            CountryId = "IOT",
                            CountryCode = "086",
                            CountryName = "British Indian Ocean Territory"
                        },
                        new
                        {
                            CountryId = "BRN",
                            CountryCode = "096",
                            CountryName = "Brunei Darussalam"
                        },
                        new
                        {
                            CountryId = "BGR",
                            CountryCode = "100",
                            CountryName = "Bulgaria"
                        },
                        new
                        {
                            CountryId = "BFA",
                            CountryCode = "854",
                            CountryName = "Burkina Faso"
                        },
                        new
                        {
                            CountryId = "BDI",
                            CountryCode = "108",
                            CountryName = "Burundi"
                        },
                        new
                        {
                            CountryId = "CPV",
                            CountryCode = "132",
                            CountryName = "Cabo Verde"
                        },
                        new
                        {
                            CountryId = "KHM",
                            CountryCode = "116",
                            CountryName = "Cambodia"
                        },
                        new
                        {
                            CountryId = "CMR",
                            CountryCode = "120",
                            CountryName = "Cameroon"
                        },
                        new
                        {
                            CountryId = "CAN",
                            CountryCode = "124",
                            CountryName = "Canada"
                        },
                        new
                        {
                            CountryId = "CYM",
                            CountryCode = "136",
                            CountryName = "Cayman Islands"
                        },
                        new
                        {
                            CountryId = "CAF",
                            CountryCode = "140",
                            CountryName = "Central African Republic"
                        },
                        new
                        {
                            CountryId = "TCD",
                            CountryCode = "148",
                            CountryName = "Chad"
                        },
                        new
                        {
                            CountryId = "CHL",
                            CountryCode = "152",
                            CountryName = "Chile"
                        },
                        new
                        {
                            CountryId = "CHN",
                            CountryCode = "156",
                            CountryName = "China"
                        },
                        new
                        {
                            CountryId = "CXR",
                            CountryCode = "162",
                            CountryName = "Christmas Island"
                        },
                        new
                        {
                            CountryId = "CCK",
                            CountryCode = "166",
                            CountryName = "Cocos (Keeling) Islands"
                        },
                        new
                        {
                            CountryId = "COL",
                            CountryCode = "170",
                            CountryName = "Colombia"
                        },
                        new
                        {
                            CountryId = "COM",
                            CountryCode = "174",
                            CountryName = "Comoros"
                        },
                        new
                        {
                            CountryId = "COG",
                            CountryCode = "178",
                            CountryName = "Congo"
                        },
                        new
                        {
                            CountryId = "COD",
                            CountryCode = "180",
                            CountryName = "Congo, Democratic Republic of the"
                        },
                        new
                        {
                            CountryId = "COK",
                            CountryCode = "184",
                            CountryName = "Cook Islands"
                        },
                        new
                        {
                            CountryId = "CRI",
                            CountryCode = "188",
                            CountryName = "Costa Rica"
                        },
                        new
                        {
                            CountryId = "CIV",
                            CountryCode = "384",
                            CountryName = "Côte d'Ivoire"
                        },
                        new
                        {
                            CountryId = "HRV",
                            CountryCode = "191",
                            CountryName = "Croatia"
                        },
                        new
                        {
                            CountryId = "CUB",
                            CountryCode = "192",
                            CountryName = "Cuba"
                        },
                        new
                        {
                            CountryId = "CUW",
                            CountryCode = "531",
                            CountryName = "Curaçao"
                        },
                        new
                        {
                            CountryId = "CYP",
                            CountryCode = "196",
                            CountryName = "Cyprus"
                        },
                        new
                        {
                            CountryId = "CZE",
                            CountryCode = "203",
                            CountryName = "Czechia"
                        },
                        new
                        {
                            CountryId = "DNK",
                            CountryCode = "208",
                            CountryName = "Denmark"
                        },
                        new
                        {
                            CountryId = "DJI",
                            CountryCode = "262",
                            CountryName = "Djibouti"
                        },
                        new
                        {
                            CountryId = "DMA",
                            CountryCode = "212",
                            CountryName = "Dominica"
                        },
                        new
                        {
                            CountryId = "DOM",
                            CountryCode = "214",
                            CountryName = "Dominican Republic"
                        },
                        new
                        {
                            CountryId = "ECU",
                            CountryCode = "218",
                            CountryName = "Ecuador"
                        },
                        new
                        {
                            CountryId = "EGY",
                            CountryCode = "818",
                            CountryName = "Egypt"
                        },
                        new
                        {
                            CountryId = "SLV",
                            CountryCode = "222",
                            CountryName = "El Salvador"
                        },
                        new
                        {
                            CountryId = "GNQ",
                            CountryCode = "226",
                            CountryName = "Equatorial Guinea"
                        },
                        new
                        {
                            CountryId = "ERI",
                            CountryCode = "232",
                            CountryName = "Eritrea"
                        },
                        new
                        {
                            CountryId = "EST",
                            CountryCode = "233",
                            CountryName = "Estonia"
                        },
                        new
                        {
                            CountryId = "SWZ",
                            CountryCode = "748",
                            CountryName = "Eswatini"
                        },
                        new
                        {
                            CountryId = "ETH",
                            CountryCode = "231",
                            CountryName = "Ethiopia"
                        },
                        new
                        {
                            CountryId = "FLK",
                            CountryCode = "238",
                            CountryName = "Falkland Islands (Malvinas)"
                        },
                        new
                        {
                            CountryId = "FRO",
                            CountryCode = "234",
                            CountryName = "Faroe Islands"
                        },
                        new
                        {
                            CountryId = "FJI",
                            CountryCode = "242",
                            CountryName = "Fiji"
                        },
                        new
                        {
                            CountryId = "FIN",
                            CountryCode = "246",
                            CountryName = "Finland"
                        },
                        new
                        {
                            CountryId = "FRA",
                            CountryCode = "250",
                            CountryName = "France"
                        },
                        new
                        {
                            CountryId = "GUF",
                            CountryCode = "254",
                            CountryName = "French Guiana"
                        },
                        new
                        {
                            CountryId = "PYF",
                            CountryCode = "258",
                            CountryName = "French Polynesia"
                        },
                        new
                        {
                            CountryId = "ATF",
                            CountryCode = "260",
                            CountryName = "French Southern Territories"
                        },
                        new
                        {
                            CountryId = "GAB",
                            CountryCode = "266",
                            CountryName = "Gabon"
                        },
                        new
                        {
                            CountryId = "GMB",
                            CountryCode = "270",
                            CountryName = "Gambia"
                        },
                        new
                        {
                            CountryId = "GEO",
                            CountryCode = "268",
                            CountryName = "Georgia"
                        },
                        new
                        {
                            CountryId = "DEU",
                            CountryCode = "276",
                            CountryName = "Germany"
                        },
                        new
                        {
                            CountryId = "GHA",
                            CountryCode = "288",
                            CountryName = "Ghana"
                        },
                        new
                        {
                            CountryId = "GIB",
                            CountryCode = "292",
                            CountryName = "Gibraltar"
                        },
                        new
                        {
                            CountryId = "GRC",
                            CountryCode = "300",
                            CountryName = "Greece"
                        },
                        new
                        {
                            CountryId = "GRL",
                            CountryCode = "304",
                            CountryName = "Greenland"
                        },
                        new
                        {
                            CountryId = "GRD",
                            CountryCode = "308",
                            CountryName = "Grenada"
                        },
                        new
                        {
                            CountryId = "GLP",
                            CountryCode = "312",
                            CountryName = "Guadeloupe"
                        },
                        new
                        {
                            CountryId = "GUM",
                            CountryCode = "316",
                            CountryName = "Guam"
                        },
                        new
                        {
                            CountryId = "GTM",
                            CountryCode = "320",
                            CountryName = "Guatemala"
                        },
                        new
                        {
                            CountryId = "GGY",
                            CountryCode = "831",
                            CountryName = "Guernsey"
                        },
                        new
                        {
                            CountryId = "GIN",
                            CountryCode = "324",
                            CountryName = "Guinea"
                        },
                        new
                        {
                            CountryId = "GNB",
                            CountryCode = "624",
                            CountryName = "Guinea-Bissau"
                        },
                        new
                        {
                            CountryId = "GUY",
                            CountryCode = "328",
                            CountryName = "Guyana"
                        },
                        new
                        {
                            CountryId = "HTI",
                            CountryCode = "332",
                            CountryName = "Haiti"
                        },
                        new
                        {
                            CountryId = "HMD",
                            CountryCode = "334",
                            CountryName = "Heard Island and McDonald Islands"
                        },
                        new
                        {
                            CountryId = "VAT",
                            CountryCode = "336",
                            CountryName = "Holy See"
                        },
                        new
                        {
                            CountryId = "HND",
                            CountryCode = "340",
                            CountryName = "Honduras"
                        },
                        new
                        {
                            CountryId = "HKG",
                            CountryCode = "344",
                            CountryName = "Hong Kong"
                        },
                        new
                        {
                            CountryId = "HUN",
                            CountryCode = "348",
                            CountryName = "Hungary"
                        },
                        new
                        {
                            CountryId = "ISL",
                            CountryCode = "352",
                            CountryName = "Iceland"
                        },
                        new
                        {
                            CountryId = "IND",
                            CountryCode = "356",
                            CountryName = "India"
                        },
                        new
                        {
                            CountryId = "IDN",
                            CountryCode = "360",
                            CountryName = "Indonesia"
                        },
                        new
                        {
                            CountryId = "IRN",
                            CountryCode = "364",
                            CountryName = "Iran (Islamic Republic of)"
                        },
                        new
                        {
                            CountryId = "IRQ",
                            CountryCode = "368",
                            CountryName = "Iraq"
                        },
                        new
                        {
                            CountryId = "IRL",
                            CountryCode = "372",
                            CountryName = "Ireland"
                        },
                        new
                        {
                            CountryId = "IMN",
                            CountryCode = "833",
                            CountryName = "Isle of Man"
                        },
                        new
                        {
                            CountryId = "ISR",
                            CountryCode = "376",
                            CountryName = "Israel"
                        },
                        new
                        {
                            CountryId = "ITA",
                            CountryCode = "380",
                            CountryName = "Italy"
                        },
                        new
                        {
                            CountryId = "JAM",
                            CountryCode = "388",
                            CountryName = "Jamaica"
                        },
                        new
                        {
                            CountryId = "JPN",
                            CountryCode = "392",
                            CountryName = "Japan"
                        },
                        new
                        {
                            CountryId = "JEY",
                            CountryCode = "832",
                            CountryName = "Jersey"
                        },
                        new
                        {
                            CountryId = "JOR",
                            CountryCode = "400",
                            CountryName = "Jordan"
                        },
                        new
                        {
                            CountryId = "KAZ",
                            CountryCode = "398",
                            CountryName = "Kazakhstan"
                        },
                        new
                        {
                            CountryId = "KEN",
                            CountryCode = "404",
                            CountryName = "Kenya"
                        },
                        new
                        {
                            CountryId = "KIR",
                            CountryCode = "296",
                            CountryName = "Kiribati"
                        },
                        new
                        {
                            CountryId = "PRK",
                            CountryCode = "408",
                            CountryName = "Korea (Democratic People's Republic of)"
                        },
                        new
                        {
                            CountryId = "KOR",
                            CountryCode = "410",
                            CountryName = "Korea, Republic of"
                        },
                        new
                        {
                            CountryId = "KWT",
                            CountryCode = "414",
                            CountryName = "Kuwait"
                        },
                        new
                        {
                            CountryId = "KGZ",
                            CountryCode = "417",
                            CountryName = "Kyrgyzstan"
                        },
                        new
                        {
                            CountryId = "LAO",
                            CountryCode = "418",
                            CountryName = "Lao People's Democratic Republic"
                        },
                        new
                        {
                            CountryId = "LVA",
                            CountryCode = "428",
                            CountryName = "Latvia"
                        },
                        new
                        {
                            CountryId = "LBN",
                            CountryCode = "422",
                            CountryName = "Lebanon"
                        },
                        new
                        {
                            CountryId = "LSO",
                            CountryCode = "426",
                            CountryName = "Lesotho"
                        },
                        new
                        {
                            CountryId = "LBR",
                            CountryCode = "430",
                            CountryName = "Liberia"
                        },
                        new
                        {
                            CountryId = "LBY",
                            CountryCode = "434",
                            CountryName = "Libya"
                        },
                        new
                        {
                            CountryId = "LIE",
                            CountryCode = "438",
                            CountryName = "Liechtenstein"
                        },
                        new
                        {
                            CountryId = "LTU",
                            CountryCode = "440",
                            CountryName = "Lithuania"
                        },
                        new
                        {
                            CountryId = "LUX",
                            CountryCode = "442",
                            CountryName = "Luxembourg"
                        },
                        new
                        {
                            CountryId = "MAC",
                            CountryCode = "446",
                            CountryName = "Macao"
                        },
                        new
                        {
                            CountryId = "MDG",
                            CountryCode = "450",
                            CountryName = "Madagascar"
                        },
                        new
                        {
                            CountryId = "MWI",
                            CountryCode = "454",
                            CountryName = "Malawi"
                        },
                        new
                        {
                            CountryId = "MYS",
                            CountryCode = "458",
                            CountryName = "Malaysia"
                        },
                        new
                        {
                            CountryId = "MDV",
                            CountryCode = "462",
                            CountryName = "Maldives"
                        },
                        new
                        {
                            CountryId = "MLI",
                            CountryCode = "466",
                            CountryName = "Mali"
                        },
                        new
                        {
                            CountryId = "MLT",
                            CountryCode = "470",
                            CountryName = "Malta"
                        },
                        new
                        {
                            CountryId = "MHL",
                            CountryCode = "584",
                            CountryName = "Marshall Islands"
                        },
                        new
                        {
                            CountryId = "MTQ",
                            CountryCode = "474",
                            CountryName = "Martinique"
                        },
                        new
                        {
                            CountryId = "MRT",
                            CountryCode = "478",
                            CountryName = "Mauritania"
                        },
                        new
                        {
                            CountryId = "MUS",
                            CountryCode = "480",
                            CountryName = "Mauritius"
                        },
                        new
                        {
                            CountryId = "MYT",
                            CountryCode = "175",
                            CountryName = "Mayotte"
                        },
                        new
                        {
                            CountryId = "MEX",
                            CountryCode = "484",
                            CountryName = "Mexico"
                        },
                        new
                        {
                            CountryId = "FSM",
                            CountryCode = "583",
                            CountryName = "Micronesia (Federated States of)"
                        },
                        new
                        {
                            CountryId = "MDA",
                            CountryCode = "498",
                            CountryName = "Moldova, Republic of"
                        },
                        new
                        {
                            CountryId = "MCO",
                            CountryCode = "492",
                            CountryName = "Monaco"
                        },
                        new
                        {
                            CountryId = "MNG",
                            CountryCode = "496",
                            CountryName = "Mongolia"
                        },
                        new
                        {
                            CountryId = "MNE",
                            CountryCode = "499",
                            CountryName = "Montenegro"
                        },
                        new
                        {
                            CountryId = "MSR",
                            CountryCode = "500",
                            CountryName = "Montserrat"
                        },
                        new
                        {
                            CountryId = "MAR",
                            CountryCode = "504",
                            CountryName = "Morocco"
                        },
                        new
                        {
                            CountryId = "MOZ",
                            CountryCode = "508",
                            CountryName = "Mozambique"
                        },
                        new
                        {
                            CountryId = "MMR",
                            CountryCode = "104",
                            CountryName = "Myanmar"
                        },
                        new
                        {
                            CountryId = "NAM",
                            CountryCode = "516",
                            CountryName = "Namibia"
                        },
                        new
                        {
                            CountryId = "NRU",
                            CountryCode = "520",
                            CountryName = "Nauru"
                        },
                        new
                        {
                            CountryId = "NPL",
                            CountryCode = "524",
                            CountryName = "Nepal"
                        },
                        new
                        {
                            CountryId = "NLD",
                            CountryCode = "528",
                            CountryName = "Netherlands"
                        },
                        new
                        {
                            CountryId = "NCL",
                            CountryCode = "540",
                            CountryName = "New Caledonia"
                        },
                        new
                        {
                            CountryId = "NZL",
                            CountryCode = "554",
                            CountryName = "New Zealand"
                        },
                        new
                        {
                            CountryId = "NIC",
                            CountryCode = "558",
                            CountryName = "Nicaragua"
                        },
                        new
                        {
                            CountryId = "NER",
                            CountryCode = "562",
                            CountryName = "Niger"
                        },
                        new
                        {
                            CountryId = "NGA",
                            CountryCode = "566",
                            CountryName = "Nigeria"
                        },
                        new
                        {
                            CountryId = "NIU",
                            CountryCode = "570",
                            CountryName = "Niue"
                        },
                        new
                        {
                            CountryId = "NFK",
                            CountryCode = "574",
                            CountryName = "Norfolk Island"
                        },
                        new
                        {
                            CountryId = "MKD",
                            CountryCode = "807",
                            CountryName = "North Macedonia"
                        },
                        new
                        {
                            CountryId = "MNP",
                            CountryCode = "580",
                            CountryName = "Northern Mariana Islands"
                        },
                        new
                        {
                            CountryId = "NOR",
                            CountryCode = "578",
                            CountryName = "Norway"
                        },
                        new
                        {
                            CountryId = "OMN",
                            CountryCode = "512",
                            CountryName = "Oman"
                        },
                        new
                        {
                            CountryId = "PAK",
                            CountryCode = "586",
                            CountryName = "Pakistan"
                        },
                        new
                        {
                            CountryId = "PLW",
                            CountryCode = "585",
                            CountryName = "Palau"
                        },
                        new
                        {
                            CountryId = "PSE",
                            CountryCode = "275",
                            CountryName = "Palestine, State of"
                        },
                        new
                        {
                            CountryId = "PAN",
                            CountryCode = "591",
                            CountryName = "Panama"
                        },
                        new
                        {
                            CountryId = "PNG",
                            CountryCode = "598",
                            CountryName = "Papua New Guinea"
                        },
                        new
                        {
                            CountryId = "PRY",
                            CountryCode = "600",
                            CountryName = "Paraguay"
                        },
                        new
                        {
                            CountryId = "PER",
                            CountryCode = "604",
                            CountryName = "Peru"
                        },
                        new
                        {
                            CountryId = "PHL",
                            CountryCode = "608",
                            CountryName = "Philippines"
                        },
                        new
                        {
                            CountryId = "PCN",
                            CountryCode = "612",
                            CountryName = "Pitcairn"
                        },
                        new
                        {
                            CountryId = "POL",
                            CountryCode = "616",
                            CountryName = "Poland"
                        },
                        new
                        {
                            CountryId = "PRT",
                            CountryCode = "620",
                            CountryName = "Portugal"
                        },
                        new
                        {
                            CountryId = "PRI",
                            CountryCode = "630",
                            CountryName = "Puerto Rico"
                        },
                        new
                        {
                            CountryId = "QAT",
                            CountryCode = "634",
                            CountryName = "Qatar"
                        },
                        new
                        {
                            CountryId = "REU",
                            CountryCode = "638",
                            CountryName = "Réunion"
                        },
                        new
                        {
                            CountryId = "ROU",
                            CountryCode = "642",
                            CountryName = "Romania"
                        },
                        new
                        {
                            CountryId = "RUS",
                            CountryCode = "643",
                            CountryName = "Russian Federation"
                        },
                        new
                        {
                            CountryId = "RWA",
                            CountryCode = "646",
                            CountryName = "Rwanda"
                        },
                        new
                        {
                            CountryId = "BLM",
                            CountryCode = "652",
                            CountryName = "Saint Barthélemy"
                        },
                        new
                        {
                            CountryId = "SHN",
                            CountryCode = "654",
                            CountryName = "Saint Helena, Ascension and Tristan da Cunha"
                        },
                        new
                        {
                            CountryId = "KNA",
                            CountryCode = "659",
                            CountryName = "Saint Kitts and Nevis"
                        },
                        new
                        {
                            CountryId = "LCA",
                            CountryCode = "662",
                            CountryName = "Saint Lucia"
                        },
                        new
                        {
                            CountryId = "MAF",
                            CountryCode = "663",
                            CountryName = "Saint Martin (French part)"
                        },
                        new
                        {
                            CountryId = "SPM",
                            CountryCode = "666",
                            CountryName = "Saint Pierre and Miquelon"
                        },
                        new
                        {
                            CountryId = "VCT",
                            CountryCode = "670",
                            CountryName = "Saint Vincent and the Grenadines"
                        },
                        new
                        {
                            CountryId = "WSM",
                            CountryCode = "882",
                            CountryName = "Samoa"
                        },
                        new
                        {
                            CountryId = "SMR",
                            CountryCode = "674",
                            CountryName = "San Marino"
                        },
                        new
                        {
                            CountryId = "STP",
                            CountryCode = "678",
                            CountryName = "Sao Tome and Principe"
                        },
                        new
                        {
                            CountryId = "SAU",
                            CountryCode = "682",
                            CountryName = "Saudi Arabia"
                        },
                        new
                        {
                            CountryId = "SEN",
                            CountryCode = "686",
                            CountryName = "Senegal"
                        },
                        new
                        {
                            CountryId = "SRB",
                            CountryCode = "688",
                            CountryName = "Serbia"
                        },
                        new
                        {
                            CountryId = "SYC",
                            CountryCode = "690",
                            CountryName = "Seychelles"
                        },
                        new
                        {
                            CountryId = "SLE",
                            CountryCode = "694",
                            CountryName = "Sierra Leone"
                        },
                        new
                        {
                            CountryId = "SGP",
                            CountryCode = "702",
                            CountryName = "Singapore"
                        },
                        new
                        {
                            CountryId = "SXM",
                            CountryCode = "534",
                            CountryName = "Sint Maarten (Dutch part)"
                        },
                        new
                        {
                            CountryId = "SVK",
                            CountryCode = "703",
                            CountryName = "Slovakia"
                        },
                        new
                        {
                            CountryId = "SVN",
                            CountryCode = "705",
                            CountryName = "Slovenia"
                        },
                        new
                        {
                            CountryId = "SLB",
                            CountryCode = "090",
                            CountryName = "Solomon Islands"
                        },
                        new
                        {
                            CountryId = "SOM",
                            CountryCode = "706",
                            CountryName = "Somalia"
                        },
                        new
                        {
                            CountryId = "ZAF",
                            CountryCode = "710",
                            CountryName = "South Africa"
                        },
                        new
                        {
                            CountryId = "SGS",
                            CountryCode = "239",
                            CountryName = "South Georgia and the South Sandwich Islands"
                        },
                        new
                        {
                            CountryId = "SSD",
                            CountryCode = "728",
                            CountryName = "South Sudan"
                        },
                        new
                        {
                            CountryId = "ESP",
                            CountryCode = "724",
                            CountryName = "Spain"
                        },
                        new
                        {
                            CountryId = "LKA",
                            CountryCode = "144",
                            CountryName = "Sri Lanka"
                        },
                        new
                        {
                            CountryId = "SDN",
                            CountryCode = "729",
                            CountryName = "Sudan"
                        },
                        new
                        {
                            CountryId = "SUR",
                            CountryCode = "740",
                            CountryName = "SuricountryName"
                        },
                        new
                        {
                            CountryId = "SJM",
                            CountryCode = "744",
                            CountryName = "Svalbard and Jan Mayen"
                        },
                        new
                        {
                            CountryId = "SWE",
                            CountryCode = "752",
                            CountryName = "Sweden"
                        },
                        new
                        {
                            CountryId = "CHE",
                            CountryCode = "756",
                            CountryName = "Switzerland"
                        },
                        new
                        {
                            CountryId = "SYR",
                            CountryCode = "760",
                            CountryName = "Syrian Arab Republic"
                        },
                        new
                        {
                            CountryId = "TWN",
                            CountryCode = "158",
                            CountryName = "Taiwan, Province of China"
                        },
                        new
                        {
                            CountryId = "TJK",
                            CountryCode = "762",
                            CountryName = "Tajikistan"
                        },
                        new
                        {
                            CountryId = "TZA",
                            CountryCode = "834",
                            CountryName = "Tanzania, United Republic of"
                        },
                        new
                        {
                            CountryId = "THA",
                            CountryCode = "764",
                            CountryName = "Thailand"
                        },
                        new
                        {
                            CountryId = "TLS",
                            CountryCode = "626",
                            CountryName = "Timor-Leste"
                        },
                        new
                        {
                            CountryId = "TGO",
                            CountryCode = "768",
                            CountryName = "Togo"
                        },
                        new
                        {
                            CountryId = "TKL",
                            CountryCode = "772",
                            CountryName = "Tokelau"
                        },
                        new
                        {
                            CountryId = "TON",
                            CountryCode = "776",
                            CountryName = "Tonga"
                        },
                        new
                        {
                            CountryId = "TTO",
                            CountryCode = "780",
                            CountryName = "Trinidad and Tobago"
                        },
                        new
                        {
                            CountryId = "TUN",
                            CountryCode = "788",
                            CountryName = "Tunisia"
                        },
                        new
                        {
                            CountryId = "TUR",
                            CountryCode = "792",
                            CountryName = "Turkey"
                        },
                        new
                        {
                            CountryId = "TKM",
                            CountryCode = "795",
                            CountryName = "Turkmenistan"
                        },
                        new
                        {
                            CountryId = "TCA",
                            CountryCode = "796",
                            CountryName = "Turks and Caicos Islands"
                        },
                        new
                        {
                            CountryId = "TUV",
                            CountryCode = "798",
                            CountryName = "Tuvalu"
                        },
                        new
                        {
                            CountryId = "UGA",
                            CountryCode = "800",
                            CountryName = "Uganda"
                        },
                        new
                        {
                            CountryId = "UKR",
                            CountryCode = "804",
                            CountryName = "Ukraine"
                        },
                        new
                        {
                            CountryId = "ARE",
                            CountryCode = "784",
                            CountryName = "United Arab Emirates"
                        },
                        new
                        {
                            CountryId = "GBR",
                            CountryCode = "826",
                            CountryName = "United Kingdom of Great Britain and Northern Ireland"
                        },
                        new
                        {
                            CountryId = "USA",
                            CountryCode = "840",
                            CountryName = "United States of America"
                        },
                        new
                        {
                            CountryId = "UMI",
                            CountryCode = "581",
                            CountryName = "United States Minor Outlying Islands"
                        },
                        new
                        {
                            CountryId = "URY",
                            CountryCode = "858",
                            CountryName = "Uruguay"
                        },
                        new
                        {
                            CountryId = "UZB",
                            CountryCode = "860",
                            CountryName = "Uzbekistan"
                        },
                        new
                        {
                            CountryId = "VUT",
                            CountryCode = "548",
                            CountryName = "Vanuatu"
                        },
                        new
                        {
                            CountryId = "VEN",
                            CountryCode = "862",
                            CountryName = "Venezuela (Bolivarian Republic of)"
                        },
                        new
                        {
                            CountryId = "VNM",
                            CountryCode = "704",
                            CountryName = "Viet Nam"
                        },
                        new
                        {
                            CountryId = "VGB",
                            CountryCode = "092",
                            CountryName = "Virgin Islands (British)"
                        },
                        new
                        {
                            CountryId = "VIR",
                            CountryCode = "850",
                            CountryName = "Virgin Islands (U.S.)"
                        },
                        new
                        {
                            CountryId = "WLF",
                            CountryCode = "876",
                            CountryName = "Wallis and Futuna"
                        },
                        new
                        {
                            CountryId = "ESH",
                            CountryCode = "732",
                            CountryName = "Western Sahara"
                        },
                        new
                        {
                            CountryId = "YEM",
                            CountryCode = "887",
                            CountryName = "Yemen"
                        },
                        new
                        {
                            CountryId = "ZMB",
                            CountryCode = "894",
                            CountryName = "Zambia"
                        },
                        new
                        {
                            CountryId = "ZWE",
                            CountryCode = "716",
                            CountryName = "Zimbabwe"
                        });
                });

            modelBuilder.Entity("GBCSporting2021_FD_Crew.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StateProvince")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerId");

                    b.HasIndex("CountryId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            Address = "94175 Spaight Pass",
                            City = "Linköping",
                            CountryId = "CAN",
                            Email = "bferronier0@ft.com",
                            FirstName = "Briant",
                            LastName = "Ferronier",
                            Phone = "441-524-5742",
                            PostalCode = "589 41",
                            StateProvince = "Östergötland"
                        },
                        new
                        {
                            CustomerId = 2,
                            Address = "6 Carioca Street",
                            City = "Hrušovany u Brna",
                            CountryId = "CAN",
                            Email = "pparslow1@usa.gov",
                            FirstName = "Pauly",
                            LastName = "Parslow",
                            Phone = "283-811-1291",
                            PostalCode = "664 62",
                            StateProvince = "Ontario"
                        },
                        new
                        {
                            CustomerId = 3,
                            Address = "13476 Northwestern Lane",
                            City = "Mirriah",
                            CountryId = "CAN",
                            Email = "bcordle2@google.com.br",
                            FirstName = "Beret",
                            LastName = "Cordle",
                            Phone = "230-306-7553",
                            PostalCode = "664 62",
                            StateProvince = "Ontario"
                        },
                        new
                        {
                            CustomerId = 4,
                            Address = "9 Southridge Street",
                            City = "Vahdat",
                            CountryId = "USA",
                            Email = "bmcness3@techcrunch.com",
                            FirstName = "Bernard",
                            LastName = "McNess",
                            Phone = "339-957-2666",
                            PostalCode = "664 62",
                            StateProvince = "Ontario"
                        },
                        new
                        {
                            CustomerId = 5,
                            Address = "14 Arkansas Center",
                            City = "Kurortnyy",
                            CountryId = "USA",
                            Email = "rewington4@ucsd.edu",
                            FirstName = "Roberta",
                            LastName = "Ewington",
                            Phone = "588-541-4858",
                            PostalCode = "197738",
                            StateProvince = "Ohio"
                        },
                        new
                        {
                            CustomerId = 6,
                            Address = "0 Algoma Point",
                            City = "Yong’an",
                            CountryId = "USA",
                            Email = "rblaxley5@skyrock.com",
                            FirstName = "Ricoriki",
                            LastName = "Blaxley",
                            Phone = "340-227-0604",
                            PostalCode = "664 62",
                            StateProvince = "Ontario"
                        },
                        new
                        {
                            CustomerId = 7,
                            Address = "5657 Mariners Cove Terrace",
                            City = "Zamarski",
                            CountryId = "USA",
                            Email = "gshay6@epa.gov",
                            FirstName = "Garey",
                            LastName = "Shay",
                            Phone = "953-845-7062",
                            PostalCode = "43-419",
                            StateProvince = "Arizona"
                        },
                        new
                        {
                            CustomerId = 8,
                            Address = "4187 Mitchell Center",
                            City = "Martapura",
                            CountryId = "USA",
                            Email = "syurocjkin7@hud.gov",
                            FirstName = "Stanislaus",
                            LastName = "Yurocjkin",
                            Phone = "250-839-9907",
                            PostalCode = "66699",
                            StateProvince = "Mars"
                        },
                        new
                        {
                            CustomerId = 9,
                            Address = "09265 Lukken Way",
                            City = "Wręczyca Wielka",
                            CountryId = "USA",
                            Email = "bspicer8@google.it",
                            FirstName = "Bendicty",
                            LastName = "Spicer",
                            Phone = "740-985-6558",
                            PostalCode = "42-284",
                            StateProvince = "Pluto"
                        },
                        new
                        {
                            CustomerId = 10,
                            Address = "24223 Birchwood Junction",
                            City = "Casais",
                            CountryId = "USA",
                            Email = "fboydell9@ustream.tv",
                            FirstName = "Faydra",
                            LastName = "Boydell",
                            Phone = "739-139-5608",
                            PostalCode = "3100-806",
                            StateProvince = "Leiria"
                        },
                        new
                        {
                            CustomerId = 11,
                            Address = "58 Dwight Avenue",
                            City = "Cayna",
                            CountryId = "USA",
                            Email = "amordea@ca.gov",
                            FirstName = "Archaimbaud",
                            LastName = "Morde",
                            Phone = "121-134-1498",
                            PostalCode = "234234",
                            StateProvince = "Ontario"
                        },
                        new
                        {
                            CustomerId = 12,
                            Address = "9565 Hoepker Point",
                            City = "Nagorsk",
                            CountryId = "USA",
                            Email = "spitbladob@yelp.com",
                            FirstName = "Susanne",
                            LastName = "Pitblado",
                            Phone = "491-587-2265",
                            PostalCode = "613261",
                            StateProvince = "New York"
                        },
                        new
                        {
                            CustomerId = 13,
                            Address = "2 Donald Center",
                            City = "Ārt Khwājah",
                            CountryId = "USA",
                            Email = "ldoulc@sciencedaily.com",
                            FirstName = "Lyon",
                            LastName = "Doul",
                            Phone = "904-538-4032",
                            PostalCode = "22233",
                            StateProvince = "Alberta"
                        },
                        new
                        {
                            CustomerId = 14,
                            Address = "70574 Warrior Parkway",
                            City = "Bealanana",
                            CountryId = "USA",
                            Email = "kbraithwaited@dailymotion.com",
                            FirstName = "Kaitlynn",
                            LastName = "Braithwaite",
                            Phone = "712-460-6508",
                            PostalCode = "22345",
                            StateProvince = "Newfoundland"
                        },
                        new
                        {
                            CustomerId = 15,
                            Address = "870 Milwaukee Street",
                            City = "Puncaksari",
                            CountryId = "USA",
                            Email = "sgeroe@google.ru",
                            FirstName = "Suzy",
                            LastName = "Gero",
                            Phone = "163-910-1575",
                            PostalCode = "543643",
                            StateProvince = "Florida"
                        });
                });

            modelBuilder.Entity("GBCSporting2021_FD_Crew.Models.Incident", b =>
                {
                    b.Property<int>("IncidentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("TechnicianId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("dateClosed")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateOpened")
                        .HasColumnType("datetime2");

                    b.HasKey("IncidentId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ProductId");

                    b.HasIndex("TechnicianId");

                    b.ToTable("Incidents");

                    b.HasData(
                        new
                        {
                            IncidentId = 1,
                            CustomerId = 2,
                            Description = "This is a seeded description placeholder",
                            ProductId = 3,
                            TechnicianId = 4,
                            Title = "I'm tryin' Captain, can't reach the button",
                            dateClosed = new DateTime(2020, 6, 14, 6, 41, 13, 0, DateTimeKind.Unspecified),
                            dateOpened = new DateTime(2020, 6, 10, 3, 41, 13, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            IncidentId = 2,
                            CustomerId = 1,
                            Description = "This is a seeded description placeholder",
                            ProductId = 5,
                            TechnicianId = 4,
                            Title = "Tester's Delight Error",
                            dateClosed = new DateTime(2020, 6, 14, 12, 41, 13, 0, DateTimeKind.Unspecified),
                            dateOpened = new DateTime(2020, 6, 10, 3, 41, 13, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            IncidentId = 3,
                            CustomerId = 9,
                            Description = "This is a seeded description placeholder",
                            ProductId = 4,
                            TechnicianId = 6,
                            Title = "To be or not to be",
                            dateClosed = new DateTime(2020, 6, 14, 17, 41, 13, 0, DateTimeKind.Unspecified),
                            dateOpened = new DateTime(2020, 6, 10, 3, 21, 13, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("GBCSporting2021_FD_Crew.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Price = 7.54m,
                            ProductCode = "HOCK21",
                            ProductName = "Hockey PPV 2021",
                            ReleaseDate = new DateTime(2020, 6, 14, 6, 41, 13, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProductId = 2,
                            Price = 9.68m,
                            ProductCode = "SOCK01",
                            ProductName = "Soccer Hooligan Fights 1.0",
                            ReleaseDate = new DateTime(2020, 10, 20, 2, 58, 26, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProductId = 3,
                            Price = 7.07m,
                            ProductCode = "ROCK02",
                            ProductName = "Rock Throwing Championship 2.0",
                            ReleaseDate = new DateTime(2020, 8, 8, 19, 58, 8, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProductId = 4,
                            Price = 3.87m,
                            ProductCode = "ZUCKHUNT",
                            ProductName = "Hunting Finals - Zuckerberg edition",
                            ReleaseDate = new DateTime(2020, 4, 29, 18, 6, 30, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProductId = 5,
                            Price = 8.38m,
                            ProductCode = "COUCH20",
                            ProductName = "Couch Potato Faceoff PPV Event",
                            ReleaseDate = new DateTime(2021, 1, 30, 17, 57, 14, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("GBCSporting2021_FD_Crew.Models.Registration", b =>
                {
                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "CustomerId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Registrations");
                });

            modelBuilder.Entity("GBCSporting2021_FD_Crew.Models.Technician", b =>
                {
                    b.Property<int>("TechnicianId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TechnicianId");

                    b.ToTable("Technicians");

                    b.HasData(
                        new
                        {
                            TechnicianId = 1,
                            Email = "nformoy0@shinystat.com",
                            Name = "Neil Formoy",
                            Phone = "(166) 8471988"
                        },
                        new
                        {
                            TechnicianId = 2,
                            Email = "smichieli1@ucla.edu",
                            Name = "Stoddard Michieli",
                            Phone = "(352) 3948039"
                        },
                        new
                        {
                            TechnicianId = 3,
                            Email = "splaskett2@diigo.com",
                            Name = "Saunderson Plaskett",
                            Phone = "(641) 8705955"
                        },
                        new
                        {
                            TechnicianId = 4,
                            Email = "klynthal3@bloomberg.com",
                            Name = "Kylen Lynthal",
                            Phone = "(385) 9669354"
                        },
                        new
                        {
                            TechnicianId = 5,
                            Email = "cmathy4@google.co.uk",
                            Name = "Clari Mathy",
                            Phone = "(928) 1519176"
                        },
                        new
                        {
                            TechnicianId = 6,
                            Email = "ccracknall5@t-online.de",
                            Name = "Cullen Cracknall",
                            Phone = "(396) 2561309"
                        },
                        new
                        {
                            TechnicianId = 7,
                            Email = "amixture6@mapquest.com",
                            Name = "Alisander Mixture",
                            Phone = "(539) 9826601"
                        },
                        new
                        {
                            TechnicianId = 8,
                            Email = "hbaumford7@alibaba.com",
                            Name = "Hugh Baumford",
                            Phone = "(313) 6544268"
                        },
                        new
                        {
                            TechnicianId = 9,
                            Email = "tdearnly8@amazon.co.uk",
                            Name = "Tybi Dearnly",
                            Phone = "(945) 9132417"
                        },
                        new
                        {
                            TechnicianId = 10,
                            Email = "bbedson9@skyrock.com",
                            Name = "Bobina Bedson",
                            Phone = "(582) 6930219"
                        },
                        new
                        {
                            TechnicianId = 11,
                            Email = "jcopyna@marriott.com",
                            Name = "Joni Copyn",
                            Phone = "(658) 2184530"
                        },
                        new
                        {
                            TechnicianId = 12,
                            Email = "tzanninib@php.net",
                            Name = "Travus Zannini",
                            Phone = "(881) 1956460"
                        },
                        new
                        {
                            TechnicianId = 13,
                            Email = "rcorradic@tuttocitta.it",
                            Name = "Rois Corradi",
                            Phone = "(854) 8298792"
                        },
                        new
                        {
                            TechnicianId = 14,
                            Email = "lmaryond@topsy.com",
                            Name = "Linn Maryon",
                            Phone = "(282) 7960687"
                        },
                        new
                        {
                            TechnicianId = 15,
                            Email = "mpeffere@thetimes.co.uk",
                            Name = "Margery Peffer",
                            Phone = "(786) 3655469"
                        },
                        new
                        {
                            TechnicianId = 16,
                            Email = "vwoodyearf@ted.com",
                            Name = "Van Woodyear",
                            Phone = "(878) 8746082"
                        },
                        new
                        {
                            TechnicianId = 17,
                            Email = "dbeverageg@aboutads.info",
                            Name = "Doll Beverage",
                            Phone = "(186) 8941499"
                        },
                        new
                        {
                            TechnicianId = 18,
                            Email = "syeabsleyh@mapquest.com",
                            Name = "Salome Yeabsley",
                            Phone = "(196) 4370797"
                        },
                        new
                        {
                            TechnicianId = 19,
                            Email = "dbucheri@pbs.org",
                            Name = "Di Bucher",
                            Phone = "(658) 6414862"
                        },
                        new
                        {
                            TechnicianId = 20,
                            Email = "kkernockej@netvibes.com",
                            Name = "Kelcy Kernocke",
                            Phone = "(495) 1613647"
                        },
                        new
                        {
                            TechnicianId = 21,
                            Email = "akincaidk@mozilla.com",
                            Name = "Augustine Kincaid",
                            Phone = "(637) 9140087"
                        },
                        new
                        {
                            TechnicianId = 22,
                            Email = "kharwinl@seesaa.net",
                            Name = "Karel Harwin",
                            Phone = "(139) 1248750"
                        },
                        new
                        {
                            TechnicianId = 23,
                            Email = "lcarrodusm@cloudflare.com",
                            Name = "Lexy Carrodus",
                            Phone = "(546) 5259083"
                        },
                        new
                        {
                            TechnicianId = 24,
                            Email = "rgregoren@alexa.com",
                            Name = "Reg Gregore",
                            Phone = "(497) 9522755"
                        },
                        new
                        {
                            TechnicianId = 25,
                            Email = "hpagano@alibaba.com",
                            Name = "Henri Pagan",
                            Phone = "(673) 5337764"
                        },
                        new
                        {
                            TechnicianId = 26,
                            Email = "msimoncellip@vimeo.com",
                            Name = "Magnum Simoncelli",
                            Phone = "(173) 9479908"
                        },
                        new
                        {
                            TechnicianId = 27,
                            Email = "clamboleq@latimes.com",
                            Name = "Clarence Lambole",
                            Phone = "(488) 5840432"
                        },
                        new
                        {
                            TechnicianId = 28,
                            Email = "ttrobeyr@rediff.com",
                            Name = "Tillie Trobey",
                            Phone = "(414) 6765629"
                        },
                        new
                        {
                            TechnicianId = 29,
                            Email = "svasilkovs@bigcartel.com",
                            Name = "Stanwood Vasilkov",
                            Phone = "(745) 5655554"
                        },
                        new
                        {
                            TechnicianId = 30,
                            Email = "grobertsent@rambler.ru",
                            Name = "Gelya Robertsen",
                            Phone = "(931) 7061643"
                        });
                });

            modelBuilder.Entity("GBCSporting2021_FD_Crew.Models.Customer", b =>
                {
                    b.HasOne("GBCSporting2021_FD_Crew.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("GBCSporting2021_FD_Crew.Models.Incident", b =>
                {
                    b.HasOne("GBCSporting2021_FD_Crew.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GBCSporting2021_FD_Crew.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GBCSporting2021_FD_Crew.Models.Technician", "Technician")
                        .WithMany()
                        .HasForeignKey("TechnicianId");

                    b.Navigation("Customer");

                    b.Navigation("Product");

                    b.Navigation("Technician");
                });

            modelBuilder.Entity("GBCSporting2021_FD_Crew.Models.Registration", b =>
                {
                    b.HasOne("GBCSporting2021_FD_Crew.Models.Product", "Product")
                        .WithMany("Registrations")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GBCSporting2021_FD_Crew.Models.Customer", "Customer")
                        .WithMany("Registrations")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("GBCSporting2021_FD_Crew.Models.Customer", b =>
                {
                    b.Navigation("Registrations");
                });

            modelBuilder.Entity("GBCSporting2021_FD_Crew.Models.Product", b =>
                {
                    b.Navigation("Registrations");
                });
#pragma warning restore 612, 618
        }
    }
}
